select
	orden_virada,
    nro_boya,
    rumbo,
    cant_trampas,
    distancia_entre_trampas,
    centolla_total,
    centolla_comercial,
    arania_total,
    canastos_procesados,
    cluster_por_canasto,
    investigacion,
    date_format(date(fecha_hora_ini_calado), '%d/%m/%Y') as fecha_ini_calado,
    LEFT(time(fecha_hora_ini_calado),5) as hora_ini_calado,
    date_format(date(fecha_hora_fin_calado), '%d/%m/%Y') as fecha_fin_calado,
    LEFT(time(fecha_hora_fin_calado),5) as hora_fin_calado,
    prof_ini_calado,
    prof_fin_calado,
    CONCAT(FLOOR(lat_ini_calado),'° ',
    MID(lat_ini_calado,4,2),',',
    MID(lat_ini_calado,6,2),'´') as lat_ini_calado,
    CONCAT(FLOOR(long_ini_calado),'° ',
    MID(long_ini_calado,4,2),',',
    MID(long_ini_calado,6,2),'´') as long_ini_calado,
    CONCAT(FLOOR(lat_fin_calado),'° ',
    MID(lat_fin_calado,4,2),',',
    MID(lat_fin_calado,6,2),'´') as lat_fin_calado,
    CONCAT(FLOOR(long_fin_calado),'° ',
    MID(long_fin_calado,4,2),',',
    MID(long_fin_calado,6,2),'´') as long_fin_calado,
    date_format(date(fecha_hora_ini_virada), '%d/%m/%Y') as fecha_ini_virada,
    LEFT(time(fecha_hora_ini_virada),5) as hora_ini_virada,
    date_format(date(fecha_hora_fin_virada), '%d/%m/%Y') as fecha_fin_virada,
    LEFT(time(fecha_hora_fin_virada),5) as hora_fin_virada,
    prof_ini_virada,
    prof_fin_virada,
    CONCAT(FLOOR(lat_ini_virada),'° ',
    MID(lat_ini_virada,4,2),',',
    MID(lat_ini_virada,6,2),'´') as lat_ini_virada,
    CONCAT(FLOOR(long_ini_virada),'° ',
    MID(long_ini_virada,4,2),',',
    MID(long_ini_virada,6,2),'´') as long_ini_virada,
    CONCAT(FLOOR(lat_fin_virada),'° ',
    MID(lat_fin_virada,4,2),',',
    MID(lat_fin_virada,6,2),'´') as lat_fin_virada,
    CONCAT(FLOOR(long_fin_virada),'° ',
    MID(long_fin_virada,4,2),',',
    MID(long_fin_virada,6,2),'´') as long_fin_virada,
    comentarios
    
FROM v_planilla_datos_puente
WHERE idmarea=11
AND orden_virada BETWEEN 11 and 20
ORDER BY orden_virada    